# Generated by Django 2.2.5 on 2019-11-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidPage',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Invalid Page',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(unique=True, upload_to='image')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=2048)),
                ('source', models.CharField(max_length=2048)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('is_gif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
            },
        ),
    ]
