# Generated by Django 2.0.4 on 2019-11-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='size',
        ),
        migrations.AddField(
            model_name='photos',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photos',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
