# Generated by Django 2.0.4 on 2019-11-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0002_auto_20191101_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trashcan',
        ),
    ]
